# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a69c03e3f6eeaabb481e713f426ef1a361a23f46a19bf0afd88b4e708263d45ce5818ed267a0ea7114fb7d6ec154ff6c819d9c042ea3dd3f717eb17337ae4dd

test:
  secret_key_base: 0644007ffabd439fe65f1b9a0be664c776f5aa950bb03ab3d5dcf18219672735818f6bf5bf6895dffa2177e8a8dbc752c06652f8a0613e8a50379a18a8f62bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
